# Generated by Django 4.2.17 on 2025-01-12 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Название')),
                ('category_description', models.TextField(max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='Название курса')),
                ('course_duration', models.IntegerField(default=1, verbose_name='Длительность курса')),
                ('course_price', models.FloatField(default=1, verbose_name='Цена курса')),
                ('course_description', models.TextField(max_length=250, verbose_name='Описание курса')),
                ('course_for_who', models.CharField(choices=[('new', 'Начинающий'), ('middle', 'Средний'), ('pro', 'Продвинутый')], max_length=150, verbose_name='Для кого')),
                ('course_categories', models.ManyToManyField(to='api.categories', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=255, verbose_name='Название урока')),
                ('lesson_number', models.PositiveIntegerField(verbose_name='Номер урока в курсе')),
                ('lesson_description', models.TextField(max_length=300, verbose_name='Описание урока')),
                ('lesson_course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.courses', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
