# Generated by Django 4.2.17 on 2025-02-10 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Название')),
                ('category_description', models.TextField(max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='Название курса')),
                ('course_duration', models.IntegerField(default=1, verbose_name='Длительность курса (мес.)')),
                ('course_price', models.FloatField(default=1, verbose_name='Цена курса (в руб.)')),
                ('course_description', models.TextField(max_length=500, verbose_name='Описание курса')),
                ('course_for_who', models.CharField(choices=[('Для начинающих', 'Для начинающих'), ('Для продолжающих', 'Для продолжающих'), ('Для продвинутых', 'Для продвинутых'), ('Для всех', 'Для всех')], max_length=150, verbose_name='Для кого')),
                ('course_picture', models.ImageField(blank=True, null=True, upload_to='course_picture/', verbose_name='Картинка курса')),
                ('course_categories', models.ManyToManyField(to='api.categories', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='TextMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_name', models.CharField(max_length=255, verbose_name='Название текста')),
                ('text_field', models.TextField(max_length=10000, verbose_name='Текстовый материал к уроку')),
                ('text_file', models.FileField(blank=True, null=True, upload_to='text_materials/', verbose_name='Текстовый файл к уроку')),
                ('text_description', models.TextField(max_length=1000, verbose_name='Описание к тексту')),
            ],
            options={
                'verbose_name': 'Текстовый материал к уроку',
                'verbose_name_plural': 'Текстовые материалы к уроку',
            },
        ),
        migrations.CreateModel(
            name='VideoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255, verbose_name='Название видео')),
                ('video_file', models.FileField(upload_to='video_materials/', verbose_name='Видеоматериал к уроку')),
                ('video_description', models.TextField(max_length=1000, verbose_name='Описание видео')),
            ],
            options={
                'verbose_name': 'Видеоматериал',
                'verbose_name_plural': 'Видеоматериалы',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=255, verbose_name='Название урока')),
                ('lesson_number', models.PositiveIntegerField(default=0, verbose_name='Номер урока в курсе')),
                ('lesson_description', models.TextField(max_length=300, verbose_name='Описание урока')),
                ('lesson_course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.courses', verbose_name='Курс')),
                ('text_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.textmaterial', verbose_name='Текстовый материал к уроку')),
                ('video_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.videomaterial', verbose_name='Видеоматериал к уроку')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
