# Generated by Django 4.2.17 on 2025-01-12 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_name', models.CharField(max_length=255, verbose_name='Название текста')),
                ('text_file', models.TextField(max_length=10000, verbose_name='Текстовый материал к уроку')),
                ('text_description', models.TextField(max_length=1000, verbose_name='Описание к тексту')),
            ],
            options={
                'verbose_name': 'Текстовый материал к уроку',
                'verbose_name_plural': 'Текстовые материалы к уроку',
            },
        ),
        migrations.CreateModel(
            name='VideoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255, verbose_name='Название видео')),
                ('video_file', models.FileField(upload_to='video_materials/', verbose_name='Видеоматериал к уроку')),
                ('video_description', models.TextField(max_length=1000, verbose_name='Описание видео')),
            ],
            options={
                'verbose_name': 'Видеоматериал',
                'verbose_name_plural': 'Видеоматериалы',
            },
        ),
        migrations.AddField(
            model_name='lessons',
            name='text_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.textmaterial', verbose_name='Текстовый материал к уроку'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='video_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.videomaterial', verbose_name='Видеоматериал к уроку'),
        ),
    ]
