# Generated by Django 4.2.17 on 2025-01-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_textmaterial_videomaterial_lessons_text_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='lesson_number',
        ),
        migrations.AlterField(
            model_name='lessons',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Номер урока в курсе'),
        ),
    ]
