# Generated by Django 4.2.17 on 2025-01-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_lessons_lesson_number_alter_lessons_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmaterial',
            name='text_field',
            field=models.TextField(default='', max_length=10000, verbose_name='Текстовый материал к уроку'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textmaterial',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='text_materials/', verbose_name='Текстовый файл к уроку'),
        ),
    ]
