# Generated by Django 4.2.17 on 2025-01-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_textmaterial_text_field_alter_textmaterial_text_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='lesson_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер урока в курсе'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
