# Generated by Django 4.2.17 on 2025-01-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_courses_course_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_description',
            field=models.TextField(max_length=10000, verbose_name='Описание курса'),
        ),
    ]
