# Generated by Django 4.2.17 on 2025-01-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_courses_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_description',
            field=models.TextField(max_length=350, verbose_name='Описание курса'),
        ),
    ]
