# Generated by Django 4.2.17 on 2025-01-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_courses_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_for_who',
            field=models.CharField(choices=[('new', 'Для начинающих'), ('middle', 'Для продолжающих'), ('pro', 'Для продвинутых'), ('all', 'Для всех')], max_length=150, verbose_name='Для кого'),
        ),
    ]
