# Generated by Django 4.2.17 on 2025-01-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_courses_course_for_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_for_who',
            field=models.CharField(choices=[('Для начинающих', 'Для начинающих'), ('Для продолжающих', 'Для продолжающих'), ('Для продвинутых', 'Для продвинутых'), ('Для всех', 'Для всех')], max_length=150, verbose_name='Для кого'),
        ),
    ]
