# Generated by Django 4.2.17 on 2025-01-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
