# Generated by Django 4.2.17 on 2025-01-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='text_materials/', verbose_name='Текстовый файл к уроку'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video_materials/', verbose_name='Видеоматериал к уроку'),
        ),
    ]
