# Generated by Django 4.2.17 on 2025-01-24 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_lessons_text_file_alter_lessons_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='text_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.textmaterial', verbose_name='Текстовый материал к уроку'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='video_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.videomaterial', verbose_name='Видеоматериал к уроку'),
        ),
    ]
