# Generated by Django 4.2.17 on 2025-01-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_lessons_text_file_alter_lessons_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_description',
            field=models.TextField(max_length=500, verbose_name='Описание курса'),
        ),
    ]
