# Generated by Django 4.2.17 on 2025-02-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_date_of_start',
            field=models.DateField(verbose_name='Дата начала курса'),
        ),
    ]
