# Generated by Django 4.2.17 on 2025-03-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_courses_course_date_of_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255, verbose_name='Название материала')),
                ('material_description', models.TextField(max_length=500, verbose_name='Описание материала')),
                ('file', models.FileField(blank=True, null=True, upload_to='dop_materials/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Дополнительный материал',
                'verbose_name_plural': 'Дополнительные материалы',
            },
        ),
    ]
