# Generated by Django 4.2.17 on 2025-02-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
