# Generated by Django 4.2.17 on 2025-03-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_comment_remove_thread_author_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
