# Generated by Django 4.2.17 on 2025-02-14 10:08

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_telephone_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128, validators=[users.validators.validate_password]),
        ),
        migrations.AlterField(
            model_name='users',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[users.validators.validate_phone_number]),
        ),
    ]
